### ISSUE TITLE
i got an issue with the login

### ISSUE THREAD

**Issue by tclass** [fbrnc/Aoe_Static#4]
Hi,

I tested your varnish.demo.aoemedia.de Shop and I created an Account, but I can't login. I downloaded the Extension from your Website and I also get an error at the Login.  So did you test the Login? and can I use this code for Live-Systems or is it only a Proof-of-Concept. The other parts working quite well but I can't find the real problem in the Login process.

**Comment by fbrnc** [comment]
Hi, 

this bug was reported before and actually I can reproduce it on the demo instance http://varnish.demo.aoemedia.de/.

Also check the comments on http://www.fabrizio-branca.de/make-your-magento-store-fly-using-varnish.html for this problem.

Without having digged into that deeper I expect the problem to be in the session handling via ajax. As soon as I have a solution I will update this repository and leave a note here . (But that might take a while, as I have some other higher priority tasks). 

If you might come across a solution earlier please tell me, and I will include that into the module.

**Comment by tclass** [comment]
ok thx for your reply, if i find the problem I'll inform you.

**Comment by ccondrup** [comment]
I think this might be due to Magento and Varnish having different ports. This will fail the same origin policy (see [SOP](https://en.wikipedia.org/wiki/Same_origin_policy#Origin_determination_rules) and [JSONP](https://en.wikipedia.org/wiki/JSONP)).

Try setting the cookie domain for Magento. SQL:

```
SELECT * FROM core_config_data
  WHERE scope_id=0 AND path='web/cookie/cookie_domain';
```

If you get `NULL`, update your setting:

```
UPDATE core_config_data SET value = 'myshop.com'
WHERE scope_id=0 AND path='web/cookie/cookie_domain';
```

**Comment by devzorg** [comment]
What about ... ?

Starting HTTP accelerator: varnishd failed!
Message from VCC-compiler:
Unknown variable 'req.hash'
At: ('input' Line 8 Pos 9)
    set req.hash += req.url;
--------########------------

Running VCC-compiler failed, exit 1

VCL compilation failed

Varnish 3.0.3

**Comment by lukvdborne** [comment]
I was able to fix or work around this problem by setting 'web/cookie/cookie_httponly' to 0.

Set "System" ==> "Configuration" ==> "Web ==> Tab "Session Cookie Management" ==> "Use HTTP only" to "No". Hope this helps!
